//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DELFI_WHM.NET.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DBACOMEntities : DbContext
    {
        public DBACOMEntities()
            : base("name=DBACOMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblConfigLinkSync> tblConfigLinkSync { get; set; }
        public DbSet<HT_HETHONG> HT_HETHONG { get; set; }
        public DbSet<ChiTiet_LenhGiaoHang> ChiTiet_LenhGiaoHang { get; set; }
        public DbSet<ChiTietSoanHang> ChiTietSoanHang { get; set; }
        public DbSet<DM_KhachHang> DM_KhachHang { get; set; }
        public DbSet<DM_LenhGiaoHang> DM_LenhGiaoHang { get; set; }
        public DbSet<DM_LenhSanXuat> DM_LenhSanXuat { get; set; }
        public DbSet<DM_Location> DM_Location { get; set; }
        public DbSet<DM_NhaVanChuyen> DM_NhaVanChuyen { get; set; }
        public DbSet<DM_Packing> DM_Packing { get; set; }
        public DbSet<DM_Pile> DM_Pile { get; set; }
        public DbSet<DM_VatTu> DM_VatTu { get; set; }
        public DbSet<DM_Vitri> DM_Vitri { get; set; }
        public DbSet<IMG_PhieuCanCau> IMG_PhieuCanCau { get; set; }
        public DbSet<tblItems> tblItems { get; set; }
        public DbSet<DM_Certificate> DM_Certificate { get; set; }
        public DbSet<DM_CropYear> DM_CropYear { get; set; }
        public DbSet<DM_LoaiBao> DM_LoaiBao { get; set; }
        public DbSet<tblConfigScale> tblConfigScale { get; set; }
        public DbSet<DM_PurchaseContract> DM_PurchaseContract { get; set; }
        public DbSet<HT_NGUOIDUNG> HT_NGUOIDUNG { get; set; }
        public DbSet<tblBigBagConfig> tblBigBagConfig { get; set; }
        public DbSet<tblLicenseKey> tblLicenseKey { get; set; }
        public DbSet<Chitiet_LenhSanXuat> Chitiet_LenhSanXuat { get; set; }
        public DbSet<DM_PhieuCanCau> DM_PhieuCanCau { get; set; }
        public DbSet<tblLichSuSanXuatBigbagJutBag> tblLichSuSanXuatBigbagJutBag { get; set; }
        public DbSet<HIS_Phieucancau> HIS_Phieucancau { get; set; }
        public DbSet<DM_PhieuNhap> DM_PhieuNhap { get; set; }
        public DbSet<DM_PhieuXuat> DM_PhieuXuat { get; set; }
        public DbSet<WH_ChiTietNhapKho> WH_ChiTietNhapKho { get; set; }
        public DbSet<WH_ChiTietXuatKho> WH_ChiTietXuatKho { get; set; }
        public DbSet<DM_LoaiPhieuGiam> DM_LoaiPhieuGiam { get; set; }
        public DbSet<Log_PhieuCanCau> Log_PhieuCanCau { get; set; }
        public DbSet<WH_TonKho> WH_TonKho { get; set; }
        public DbSet<DM_Lot> DM_Lot { get; set; }
    
        public virtual ObjectResult<string> SP_CheckLicense(string cPU, string hardware)
        {
            var cPUParameter = cPU != null ?
                new ObjectParameter("CPU", cPU) :
                new ObjectParameter("CPU", typeof(string));
    
            var hardwareParameter = hardware != null ?
                new ObjectParameter("Hardware", hardware) :
                new ObjectParameter("Hardware", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_CheckLicense", cPUParameter, hardwareParameter);
        }
    }
}
