//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DELFI_WHM.NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitiet_LenhSanXuat
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public string BatchNo { get; set; }
        public string ItemNo { get; set; }
        public string LocationCode { get; set; }
        public string BinCode { get; set; }
        public string Lot { get; set; }
        public Nullable<int> PalletQty { get; set; }
        public string PackingUnitCode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> LineNo { get; set; }
        public Nullable<bool> Status { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string PDAUser { get; set; }
        public Nullable<decimal> QtyPicked { get; set; }
        public string Note { get; set; }
    }
}
