//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DELFI_WHM.NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Lot
    {
        public string Lot { get; set; }
        public Nullable<int> Bag { get; set; }
        public string CropYear { get; set; }
        public string ItemCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Note { get; set; }
        public Nullable<int> Shift { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string BatchNo { get; set; }
        public string PackingUnitCode { get; set; }
        public string Cer { get; set; }
    }
}
