//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DELFI_WHM.NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_PhieuNhap
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public string WeightNote { get; set; }
        public string VendorName { get; set; }
        public string VendorCode { get; set; }
        public string Lot { get; set; }
        public string BinCode { get; set; }
        public string ContractNo { get; set; }
        public string VehicleNo { get; set; }
        public string UserName { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public bool Del { get; set; }
        public Nullable<bool> KhaiBao_SoBao { get; set; }
    }
}
