//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DELFI_WHM.NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Packing
    {
        public string PackageType { get; set; }
        public string PackageCode { get; set; }
        public string PackageDesc { get; set; }
        public Nullable<decimal> PackageQty { get; set; }
        public decimal Format { get; set; }
    }
}
