//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DELFI_WHM.NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_PhieuCanCau
    {
        public int ID { get; set; }
        public string LocationName { get; set; }
        public string WeightNote { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string VehicleNo { get; set; }
        public string WeightType { get; set; }
        public string ContractNo { get; set; }
        public string TransporterCode { get; set; }
        public string ItemCode { get; set; }
        public string VendorCode { get; set; }
        public string VendorName { get; set; }
        public string LocationCode { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public Nullable<System.DateTime> DateOut { get; set; }
        public Nullable<decimal> FirstWeight { get; set; }
        public Nullable<decimal> SecondWeight { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> TruckTare { get; set; }
        public Nullable<decimal> TruckQty { get; set; }
        public Nullable<decimal> PackageQty { get; set; }
        public Nullable<decimal> TotalPackageQty { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public string Note { get; set; }
        public Nullable<bool> ExportNav { get; set; }
        public Nullable<bool> Del { get; set; }
        public string UserName { get; set; }
        public string PDAUser { get; set; }
        public string PackageType { get; set; }
        public string Lot { get; set; }
        public string BinCode { get; set; }
        public string ArrayQRCode { get; set; }
        public string Certificate { get; set; }
        public string PackageCode { get; set; }
        public string UserName2 { get; set; }
    }
}
