//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DELFI_WHM.NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_Phieucancau
    {
        public int ID { get; set; }
        public Nullable<int> ID_WeightNote { get; set; }
        public Nullable<System.DateTime> Dateupdate { get; set; }
        public string UserName { get; set; }
        public string Desc { get; set; }
        public string Loai { get; set; }
        public string Ghichu { get; set; }
    }
}
