//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DELFI_WHM.NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_HETHONG
    {
        public int ID { get; set; }
        public string TENCOQUAN { get; set; }
        public string DIACHI { get; set; }
        public string DIENTHOAI { get; set; }
        public string FAX { get; set; }
        public string MAIL { get; set; }
        public string WEBSITE { get; set; }
        public string DIADIEM { get; set; }
        public string LOCATIONCODE { get; set; }
    }
}
