//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DELFI_WHM.NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_NGUOIDUNG
    {
        public int NGUOIDUNG { get; set; }
        public string TAIKHOAN { get; set; }
        public string MATKHAU { get; set; }
        public string HOTEN { get; set; }
        public Nullable<bool> HOATDONG { get; set; }
        public string KIEUGIAODIEN { get; set; }
        public string GHICHU { get; set; }
        public string QUYEN { get; set; }
        public string MENU_NGANG { get; set; }
        public string MENU_DOC { get; set; }
        public string DANH_MUC { get; set; }
        public string LINH_VUC { get; set; }
        public bool QUYENPHANQUYEN { get; set; }
        public string PathHinhAnh { get; set; }
    }
}
