//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DELFI_WHM.NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMG_PhieuCanCau
    {
        public int ID { get; set; }
        public string WeightNote { get; set; }
        public byte[] IMG1 { get; set; }
        public byte[] IMG2 { get; set; }
        public byte[] IMG3 { get; set; }
        public byte[] IMG4 { get; set; }
    }
}
