//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DELFI_WHM.NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_PhieuCanCau
    {
        public int ID { get; set; }
        public string WeightNote { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string UserName { get; set; }
        public string Ghichu { get; set; }
        public Nullable<int> LanCan { get; set; }
        public Nullable<decimal> SoCanBanDau { get; set; }
        public Nullable<decimal> SoSauKhiSua { get; set; }
        public Nullable<int> Loai { get; set; }
    }
}
