//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DELFI_WHM.NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBigBagConfig
    {
        public int ID { get; set; }
        public string LOT { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Shift { get; set; }
        public Nullable<int> Bag { get; set; }
        public string CropYear { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Note { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UserCreate { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public bool IsActive { get; set; }
        public int IDScales { get; set; }
        public string PackageType { get; set; }
        public string BatchNo { get; set; }
        public int UuTien { get; set; }
        public bool TamNgung { get; set; }
        public bool HoanThanh { get; set; }
        public int SoBaoDaSanXuat { get; set; }
    }
}
