//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DELFI_WHM.NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLichSuSanXuatBigbagJutBag
    {
        public int ID { get; set; }
        public string QRCode { get; set; }
        public string LOT { get; set; }
        public string CropYear { get; set; }
        public string ItemCode { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Note { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string PackageType { get; set; }
        public int IDScales { get; set; }
        public int IDConfig { get; set; }
        public string BatchNo { get; set; }
        public string WeightNote { get; set; }
        public string SanPhamTuCan { get; set; }
        public string SoLotTuCan { get; set; }
    }
}
