//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DELFI_WHM.NET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WH_ChiTietNhapKho
    {
        public int ID { get; set; }
        public string Document { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string QRCode { get; set; }
        public string ItemNo { get; set; }
        public string Lot { get; set; }
        public string Certificate { get; set; }
        public string PackageType { get; set; }
        public string PackageCode { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> TruckQty { get; set; }
        public Nullable<decimal> PackageQty { get; set; }
        public Nullable<decimal> TotalPackageQty { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public Nullable<decimal> QRCodeQty { get; set; }
        public string BinCode { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Sample { get; set; }
        public string Type { get; set; }
        public int IDPhieuNhap { get; set; }
        public System.TimeSpan Thoigian { get; set; }
        public int Ca { get; set; }
        public bool Del { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
